# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd66926f2d4e4a5cc4120e64532c2e06ddbed857b8224a842d5a2da148baeb2374e9e7a4dea8f223f7636fce9d2bd31b10dd4a00e70f0c3c1437e624b56ef647

test:
  secret_key_base: d2ba46f63da71d341bcfe714f133681a2ed67cc60d1b3857247e580aa40a02fd8666366a37db5972e33045f2acbf1e7ada1bfefaafce906c0691926b241d9908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
